/**
 * @file        SettingsDialog.h
 * @brief       The header file of the SettingsDialog class.
 * @author      Belinda Kneubühler
 * @date        2020-08-18
 * @copyright   GNU General Public License v2.0
 *
 * @details
 * Defines the SettingsDialog class and contains the general class description.
 */
#ifndef OBP_SETTINGSDIALOG_H
#define OBP_SETTINGSDIALOG_H



#include <QtWidgets/QDialog>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QDialogButtonBox>

#include "common.h"
//! The settings dialog displays configuration values.
/*!
 * The settings dialog is a pop-up dialog, that lets the user see and change the configuration values.
 * Processing of the values and events generated from this dialog is done in the parent widget.
 */
class SettingsDialog: public QDialog {
Q_OBJECT
public:
    SettingsDialog(QWidget *parent = 0);

    // Getter and setter methods for variables access.
    double getRatioSBP();
    void setRatioSBP(double val);
    double getRatioDBP();
    void setRatioDBP(double val);
    int getMinNbrPeaks();
    void setMinNbrPeaks(int val);
    int getPumpUpValue();
    void setPumpUpValue(int val);

signals:
    // Signals are automatically generated by the moc and must not be implemented in the .cpp file.
    void resetValues();
private slots:
    void resetClicked();
private:
    void setupUi(QDialog *SettingsDialog);
    void retranslateUi(QDialog *SettingsDialog);

    // The GUI components:
    QVBoxLayout *vlMain;
    QFormLayout *formL;
    QLabel *lRatioSBP;
    QDoubleSpinBox *dsbRatioSBP;
    QLabel *lRatioDBP;
    QDoubleSpinBox *dsbRatioDBP;
    QLabel *lMinNbrPeaks;
    QSpinBox *sbMinNbrPeaks;
    QLabel *lPumpUpValue;
    QSpinBox *sbPumpUpValue;
    QPushButton *btnReset;
    QDialogButtonBox *buttonBox;
    QLabel *lDescription;


};


#endif //OBP_SETTINGSDIALOG_H
